import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Favicon from "../../public/favicon.ico";
import Navigation from '@/app/components/Navigation'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arnav Arora",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        {children}
        </body>
    </html>
  );
}
