import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Favicon from "../../public/favicon.ico";
import Navigation from "./components/Navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arnav Arora",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  relative back`}>
      <div className="fixed top-0 w-full z-50">
        <Navigation />
      </div>
      <div className="">
      {children}
      </div>
        </body>
    </html>
  );
}
